title: Home devsh
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: Medium inspired blogging theme for Stackbit
layout_style: list
palette: green
header:
  title: devsh
  logo_img: images/logo-FINAL-S.png
  logo_img_alt: devsh
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: About
      url: /about
      style: link
footer:
  content: ''
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/tweetshweets'
      style: icon
      icon_class: fa-twitter
      new_window: true
    - label: GitHub
      url: 'https://github.com/shwetayadkikar'
      style: icon
      icon_class: fa-github
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: icon
      icon_class: fa-linkedin
      new_window: true
    - label: DEV
      url: 'https://dev.to/'
      style: icon
      icon_class: fa-dev
      new_window: true
  has_subscribe: false
  subscribe_title: Subscribe for new updates
  subscribe_content: >-
    Subscribe to my email newsletter to receive useful articles and special
    offers. This monthly email is sent out on the first of every month.
  subscribe_action: /subscribe-success
  links: []
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
favicon: images/square-sloth.png
