title: Home stratuss
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: Shweta trying to blog
layout_style: list
palette: green
header:
  title: stratuss
  logo_img: images/Stratus-96-black-big.png
  logo_img_alt: stratuss
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: About
      url: /about
      style: link
footer:
  content: ''
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/tweetshweets'
      style: icon
      icon_class: fa-twitter
      new_window: true
    - label: GitHub
      url: 'https://github.com/shwetayadkikar'
      style: icon
      icon_class: fa-github
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/shweta-yadkikar-86b11590'
      style: icon
      icon_class: fa-linkedin
      new_window: true
  has_subscribe: false
  subscribe_title: Subscribe for new updates
  subscribe_content: >-
    Subscribe to my email newsletter to receive useful articles and special
    offers. This monthly email is sent out on the first of every month.
  subscribe_action: /subscribe-success
  links: []
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
# favicon: images/square-sloth.png
